name: Build vcpkg

on:
  push:
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2    
    - name: Install vcpkg
      shell: bash
      run: |
        set +e
        git clone https://github.com/microsoft/vcpkg
        ./vcpkg/bootstrap-vcpkg.sh
    - name: Upload Artifact
      uses: actions/upload-artifact@master
      with:
        name: vcpkg
        path: ./vcpkg/vcpkg
